### ISSUE TITLE
Build Failing can't be good can it ? 

### ISSUE THREAD

**Issue by 4mig4** [d-led/luconejo#2]

**Comment by 4mig4** [comment]
As written in the subject.

**Comment by d-led** [comment]
The underlying cpp library had failing tests, which were there to document the gaps. The Lua tests simply repeat those. If the existing "green" functionality is enough for you, I'd say the library could work. But I'd recommend writing own tests and contributing to the original library should it have gaps. I didn't have time to do so myself yet

**Comment by d-led** [comment]
@4mig4 check out the test output: the 3 tests that are failing might not be of your concern, necessarily: [L1663-L1760](https://travis-ci.org/d-led/luconejo/jobs/416970985#L1663-L1760)

**Comment by 4mig4** [comment]
I see, too bad as there are no good AMQP lua libraries around.

**Comment by d-led** [comment]
@4mig4 I agree. This library can be taken further if needed, given someone has the need, the time & dedication to develop it and its dependencies
